version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlLiquibase
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    depends_on:
      - mysqlLiquibase
    networks:
      - my_network
  mysqlLiquibase:
    image: mysql:8.0
    container_name: mysqlLiquibase
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge