spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  profiles:
    active: test
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  docker:
    compose:
      enabled: false

server:
  port: 8080