databaseChangeLog:

  - changeSet:
      id: create_productdetails
      author: root
      preConditions:
        onFail: MARK_RAN
        not:
          tableExists:
            tableName: productdetails
      changes:
        - createTable:
            tableName: productdetails
            columns:
              - column:
                  name: product_details_id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: color
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: image_url
                  type: varchar(255)
                  constraints:
                    unique: true
                    nullable: false
        - addForeignKeyConstraint:
            baseTableName: products
            baseColumnNames: product_details_id
            constraintName:  fk_productdetail
            referencedTableName: productdetails
            referencedColumnNames: product_details_id
            onDelete: CASCADE
